version: '3.8'

services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --user=b2badmin --dbname=b2bdjango" ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_db:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:8.0
    container_name: "mongo_db"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
      - ./docker/mongo_db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongo_data: