version: '3.8'

services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres_db
      - DB_PORT=5432
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_db:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:latest
    container_name: "mongo_db"
    environment:
      - "MONGO_DATA_DIR=/data/db"
      - "MONGO_LOG_DIR=/dev/null"
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017

volumes:
  postgres_data:
  mongo_data: